### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by pgewebmaster** [BabDev/Yet-Another-Social-Plugin#10]
I was wondering if you could incorporate the ability to share through google+?

I found another social plugin at: http://storejextensions.org/extensions/fast_social_share.html
that gives you that option plus a pin it button.
I'm not sure that I have that much need for a pinterest button, but the ability to share through google could come in handy.

Thanks for your time,
Danielle

**Comment by mbabker** [comment]
You should already be able to do so.  See https://www.babdev.com/blog/169-joomla-3-5-features-you-won-t-hear-about as an example.

Once you click the +1 button, you should get a popup that lets you share the item.

![screen shot 2016-06-15 at 3 15 12 pm](https://cloud.githubusercontent.com/assets/368545/16095837/0b9b137e-330c-11e6-9154-c24c11eb562d.png)

**Comment by pgewebmaster** [comment]
Thanks for getting back to me.
I guess I forgot about that.  So now it looks like the other extension is showing 2 buttons to do what we can do with 1.
